"""initial schema

Revision ID: 616f098419ed
Revises:
Create Date: 2026-07-16 22:36:15.890959

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "616f098419ed"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "characters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("short_description", sa.Text(), nullable=True),
        sa.Column("persona_prompt", sa.Text(), nullable=True),
        sa.Column("nickname", sa.String(), nullable=True),
        sa.Column("scenario", sa.Text(), nullable=True),
        sa.Column("first_mes", sa.Text(), nullable=True),
        sa.Column("alternate_greetings", sa.JSON(), nullable=True),
        sa.Column("mes_example", sa.Text(), nullable=True),
        sa.Column("content_rating", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_characters_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_characters_name"), ["name"], unique=False)

    op.create_table(
        "sampler_presets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("min_p", sa.Float(), nullable=True),
        sa.Column("top_k", sa.Integer(), nullable=True),
        sa.Column("top_p", sa.Float(), nullable=True),
        sa.Column("repeat_penalty", sa.Float(), nullable=True),
        sa.Column("dry_multiplier", sa.Float(), nullable=True),
        sa.Column("dry_base", sa.Float(), nullable=True),
        sa.Column("dry_range", sa.Integer(), nullable=True),
        sa.Column("xtc_threshold", sa.Float(), nullable=True),
        sa.Column("xtc_probability", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sampler_presets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sampler_presets_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_sampler_presets_name"), ["name"], unique=True
        )

    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("instruction", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tags_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tags_label"), ["label"], unique=True)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("persona_description", sa.Text(), nullable=True),
        sa.Column("appearance", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_name"), ["name"], unique=False)
        batch_op.create_index(
            "uq_users_single_active",
            ["is_active"],
            unique=True,
            sqlite_where=sa.text("is_active"),
        )

    op.create_table(
        "character_tags",
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"], ["characters.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("character_id", "tag_id"),
    )
    op.create_table(
        "chats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.Column("current_message_id", sa.Integer(), nullable=True),
        sa.Column("active_summary", sa.Text(), nullable=True),
        sa.Column("interaction_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_id"], ["characters.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["current_message_id"],
            ["message_nodes.id"],
            name="fk_chats_current_message",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chats", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chats_character_id"), ["character_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_chats_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_chats_user_id"), ["user_id"], unique=False)

    op.create_table(
        "lorebook_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("keyword", sa.String(), nullable=True),
        sa.Column("keys", sa.JSON(), nullable=True),
        sa.Column("secondary_keys", sa.JSON(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("character_id", sa.Integer(), nullable=True),
        sa.Column("is_global", sa.Boolean(), nullable=True),
        sa.Column("insertion_order", sa.Integer(), nullable=True),
        sa.Column("probability", sa.Integer(), nullable=True),
        sa.Column("scan_depth", sa.Integer(), nullable=True),
        sa.Column("is_constant", sa.Boolean(), nullable=True),
        sa.Column("cooldown_turns", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_id"], ["characters.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lorebook_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lorebook_entries_character_id"),
            ["character_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_lorebook_entries_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_lorebook_entries_keyword"), ["keyword"], unique=False
        )

    op.create_table(
        "journal_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=True),
        sa.Column("chat_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("mood_at_time", sa.String(), nullable=True),
        sa.Column("relationship_score", sa.Integer(), nullable=True),
        sa.Column("energy_level", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_id"], ["characters.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("journal_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_journal_entries_character_id"),
            ["character_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_journal_entries_chat_id"), ["chat_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_journal_entries_id"), ["id"], unique=False)

    op.create_table(
        "message_nodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("variant_index", sa.Integer(), nullable=True),
        sa.Column("request_id", sa.String(), nullable=True),
        sa.Column("character_id", sa.Integer(), nullable=True),
        sa.Column("chat_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_id"], ["characters.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["message_nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("message_nodes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_message_nodes_character_id"), ["character_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_message_nodes_chat_id"), ["chat_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_message_nodes_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_message_nodes_request_id"), ["request_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_message_nodes_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "agent_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=True),
        sa.Column("current_message_id", sa.Integer(), nullable=True),
        sa.Column("active_chat_id", sa.Integer(), nullable=True),
        sa.Column("interaction_count", sa.Integer(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("mood", sa.String(), nullable=True),
        sa.Column("clothes", sa.String(), nullable=True),
        sa.Column("stats", sa.JSON(), nullable=True),
        sa.Column("active_summary", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["active_chat_id"], ["chats.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["character_id"], ["characters.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["current_message_id"], ["message_nodes.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_states", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_agent_states_character_id"), ["character_id"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_agent_states_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_states", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_states_id"))
        batch_op.drop_index(batch_op.f("ix_agent_states_character_id"))

    op.drop_table("agent_states")
    with op.batch_alter_table("message_nodes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_message_nodes_user_id"))
        batch_op.drop_index(batch_op.f("ix_message_nodes_request_id"))
        batch_op.drop_index(batch_op.f("ix_message_nodes_id"))
        batch_op.drop_index(batch_op.f("ix_message_nodes_chat_id"))
        batch_op.drop_index(batch_op.f("ix_message_nodes_character_id"))

    op.drop_table("message_nodes")
    with op.batch_alter_table("journal_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_journal_entries_id"))
        batch_op.drop_index(batch_op.f("ix_journal_entries_chat_id"))
        batch_op.drop_index(batch_op.f("ix_journal_entries_character_id"))

    op.drop_table("journal_entries")
    with op.batch_alter_table("lorebook_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lorebook_entries_keyword"))
        batch_op.drop_index(batch_op.f("ix_lorebook_entries_id"))
        batch_op.drop_index(batch_op.f("ix_lorebook_entries_character_id"))

    op.drop_table("lorebook_entries")
    with op.batch_alter_table("chats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chats_user_id"))
        batch_op.drop_index(batch_op.f("ix_chats_id"))
        batch_op.drop_index(batch_op.f("ix_chats_character_id"))

    op.drop_table("chats")
    op.drop_table("character_tags")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("uq_users_single_active", sqlite_where=sa.text("is_active"))
        batch_op.drop_index(batch_op.f("ix_users_name"))
        batch_op.drop_index(batch_op.f("ix_users_id"))

    op.drop_table("users")
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tags_label"))
        batch_op.drop_index(batch_op.f("ix_tags_id"))

    op.drop_table("tags")
    with op.batch_alter_table("sampler_presets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sampler_presets_name"))
        batch_op.drop_index(batch_op.f("ix_sampler_presets_id"))

    op.drop_table("sampler_presets")
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_characters_name"))
        batch_op.drop_index(batch_op.f("ix_characters_id"))

    op.drop_table("characters")
    # ### end Alembic commands ###
