"""add last_reflected_at_count

Revision ID: 886d9e36d0c1
Revises: 616f098419ed
Create Date: 2026-07-17 01:08:25.492953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '886d9e36d0c1'
down_revision: Union[str, Sequence[str], None] = '616f098419ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reflected_at_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reflected_at_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('last_reflected_at_count')

    with op.batch_alter_table('agent_states', schema=None) as batch_op:
        batch_op.drop_column('last_reflected_at_count')

    # ### end Alembic commands ###
